### ISSUE TITLE
ASDCのリリース

### ISSUE THREAD

**Issue by shirayu** [masahiro-mi/masahiro-mi.github.io#2]
以下のコーパスをリリースいたしましたので，よろしければ記載お願いいたします．

| 名前 | データ量 | 形式 | 研究利用 | 商用利用 | 概要 |  
|:---|:---|:---|:---:|:---:|:---|
| [Accommodation Search Dialog Corpus (宿泊施設探索対話コーパス)](https://github.com/megagonlabs/asdc)  | 210会話+10万以上の発話  | テキスト対話 | CC BY 4.0 | 可 | 宿泊施設を探しているカスタマーとエージェントのオンラインテキスト対話コーパス| 

Megagon Labs
林部 祐太

**Comment by masahiro-mi** [comment]
ご連絡ありがとうございます！
コーパス情報を記載させていただきます！

また、情報提供者としてお名前も載せたいと思うのですが、よろしいでしょうか？

**Comment by shirayu** [comment]
ありがとうございます．
はい，構いません！
よろしくお願いいたします．

**Comment by masahiro-mi** [comment]
ありがとうございます、コーパス一覧ページにいただいた情報を参考に追記させていただきました！
