### ISSUE TITLE
CALLFRIEND Japanese

### ISSUE THREAD

**Issue by mk-nakano** [masahiro-mi/masahiro-mi.github.io#3]
LDCにCALLFRIEND Japaneseという対話コーパスがあるようです。
https://catalog.ldc.upenn.edu/LDC96S53
よろしければご掲載ください。

**Comment by mk-nakano** [comment]
LDCだけではなくCABankにもあるようです（CallHomeと同じ）
https://ca.talkbank.org/access/CallFriend/jpn.html
- データ量 60会話（1会話5-30分）
- 形式 音声、書き起こし、話者の情報
- 利用規約 LDC User Agreement for Non-Members
- 概要 言語同定用のコーパス。北米在住の日本語母語話者の電話会話
LDCとCABankの関係が良くわかっていません。

**Comment by masahiro-mi** [comment]
情報ありがとうございます！
一覧に追記しました！！
（LDCの規約とCABankの規約のどちらが対応するのかよくわかりませんが、ページにもLDCと書いてあったのでとりあえずそちらで記載しました）
