### ISSUE TITLE
JMRDのリリース

### ISSUE THREAD

**Issue by Taka008** [masahiro-mi/masahiro-mi.github.io#4]
以下のコーパスを公開いたしましたので，よろしければリストへの追加をお願いします

|   名前  |  データ量   |  形式   |  研究利用  |  商用利用   |  概要 | 
| --- | --- | --- | --- | --- | --- | 
| [日本語映画推薦対話データセット (JMRD)](https://github.com/ku-nlp/JMRD)  | 5,075対話（約11万発話）  | テキスト | CC BY-SA 4.0 | 可 | クラウドワーカー間の映画推薦対話を収録。全ての推薦者側の発話に，推薦に使用した外部知識の情報を付与。| 

京都大学
児玉 貴志

**Comment by masahiro-mi** [comment]
コーパスリリースのお知らせありがとうございます！
ぜひ追加させていただきます！

また、情報提供者として児玉様のお名前の載せたく思いますが、いかがでしょうか。
ご確認をお願いいたします。

**Comment by Taka008** [comment]
構いません，よろしくお願いします

**Comment by masahiro-mi** [comment]
ありがとうございます！一覧ページに追加をさせていただきました！
