### ISSUE TITLE
OjousamaTalkScriptDataset

### ISSUE THREAD

**Issue by shirayu** [masahiro-mi/masahiro-mi.github.io#5]
OjousamaTalkScriptDataseというデータセットを見つけました．
なかなかユニークなデータだと思います．

| 名前 | データ量 | 形式 | 研究利用 | 商用利用 | 概要 |  
|:---|:---|:---|:---:|:---:|:---|
| [OjousamaTalkScriptDataset](https://github.com/matsuvr/OjousamaTalkScriptDataset)  | 200対話  | テキスト対話 | MITライセンス | 可 | 一般人とお嬢様の会話を模したデータセット|

**Comment by masahiro-mi** [comment]
まあ素敵！情報ありがとうございますわ！
一覧に追記させていただきましたわ！！
