### ISSUE TITLE
ゲームの会話データ

### ISSUE THREAD

**Issue by shirayu** [masahiro-mi/masahiro-mi.github.io#6]
純粋な会話だけではありませんが，非常にユニークで，しかも活用しやすいライセンスです

| 名前 | データ量 | 形式 | 研究利用 | 商用利用 | 概要 |  
|:---|:---|:---|:---:|:---:|:---|
| [Roseblue ゲームシナリオ](https://gitlab.com/open_contents_datasets/Rosebleu)  | 約550万文字  | テキスト対話 | Apache License 2.0 | 可 |10タイトルのゲームのシナリオから作成したデータセット | 
|[character conversation dataset](https://github.com/matsuvr/characterconversationdataset) | 約2万文字  | テキスト対話 |Apache License 2.0| 可 |公開終了の同人ゲームのシナリオデータから作成した会話データ | 

- 関連リンク: https://open_contents_datasets.gitlab.io/project_home/

**Comment by masahiro-mi** [comment]
情報ありがとうございます！
コーパス一覧ページに追加させていただきました！
