### ISSUE TITLE
megagonlabs/instruction_ja

### ISSUE THREAD

**Issue by shirayu** [masahiro-mi/masahiro-mi.github.io#7]
| 名前 | データ量 | 形式 | 研究利用 | 商用利用 | 概要 |  
|:---|:---|:---|:---:|:---:|:---|
| [megagonlabs/instruction_ja](https://github.com/megagonlabs/instruction_ja) |669対話  | テキスト対話 | MITライセンス | 可 |[kunishou/hh-rlhf-49k-ja](https://huggingface.co/datasets/kunishou/hh-rlhf-49k-ja)の一部を人手で改変して自然な日本語表現にした日本語指示データ | 

- 関連リンク: https://www.megagon.ai/jp/blog/instruction-and-reviews/

**Comment by masahiro-mi** [comment]
ありがとうございます！こちらも追加しました！
