### ISSUE TITLE
BPersona-chatのURLの誤り

### ISSUE THREAD

**Issue by yamasy1549** [masahiro-mi/masahiro-mi.github.io#8]
BPersona-chatの正しいURLは https://github.com/cl-tohoku/BPersona-chat でしょうか。

（issueとは関係ありませんが……東中研究室で公開している RealPersonaChat および JMultiWOZ を掲載していただきうれしいです。ありがとうございます 🙇 ）

**Comment by masahiro-mi** [comment]
修正情報ありがとうございます！反映しておきます！

また，情報提供者として掲載して宜しければ所属とお名前ご記入いただければと思います，よろしくお願いいたします！

**Comment by yamasy1549** [comment]
@masahiro-mi 反映していただきありがとうございます。
所属は名古屋大学、名前は山下 紗苗です。よろしくお願いいたします 🙏
